# Generated by Django 6.0.3 on 2026-03-22 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_first', models.CharField(help_text='Sortable name: Last, First M.', max_length=200, verbose_name='Last, First')),
                ('name', models.CharField(help_text='Full display name: First M. Last', max_length=200, verbose_name='Display Name')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('classification', models.CharField(choices=[('faculty', 'Faculty'), ('staff', 'Staff')], db_index=True, default='faculty', max_length=10)),
                ('rank', models.CharField(blank=True, max_length=350)),
                ('department', models.CharField(blank=True, choices=[('biology', 'Biology'), ('chemistry', 'Chemistry'), ('mathematics', 'Mathematical Sciences'), ('physics', 'Physics'), ('asme', 'Aerospace & Mechanical Engineering'), ('ceet', 'Chemical Engineering & Environmental Toxicology'), ('cets', 'Civil Engineering & Transportation Studies'), ('eecs', 'Electrical Engineering & Computer Science'), ('deans-office', "Dean's Office")], help_text='Primary department affiliation', max_length=20, null=True, verbose_name='Department')),
                ('admin_role', models.CharField(blank=True, help_text='e.g. Department Chair, Program Director', max_length=100, verbose_name='Administrative Role')),
                ('room', models.CharField(blank=True, help_text='e.g. TECH 206', max_length=50, null=True, verbose_name='Room')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, help_text='(713) 313.4482', max_length=30)),
                ('cv_link', models.URLField(blank=True, help_text='e.g. https://live-tsu-hb2504.pantheonsite.io/wp-content/uploads/cv/harvey-mark-cv.pdf', verbose_name='CV Link')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='person_photos/', verbose_name='Photo')),
                ('biography', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['last_first'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, choices=[('biology', 'Biology'), ('chemistry', 'Chemistry'), ('mathematics', 'Mathematical Sciences'), ('physics', 'Physics'), ('asme', 'Aerospace & Mechanical Engineering'), ('ceet', 'Chemical Engineering & Environmental Toxicology'), ('cets', 'Civil Engineering & Transportation Studies'), ('eecs', 'Electrical Engineering & Computer Science'), ('deans-office', "Dean's Office")], help_text='Primary department affiliation', max_length=20, null=True, verbose_name='Department')),
                ('lecture_credits', models.DecimalField(decimal_places=1, default=3, max_digits=4)),
                ('lab_credits', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='core.course')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['department', 'code'],
                'unique_together': {('department', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('department', models.CharField(blank=True, choices=[('biology', 'Biology'), ('chemistry', 'Chemistry'), ('mathematics', 'Mathematical Sciences'), ('physics', 'Physics'), ('asme', 'Aerospace & Mechanical Engineering'), ('ceet', 'Chemical Engineering & Environmental Toxicology'), ('cets', 'Civil Engineering & Transportation Studies'), ('eecs', 'Electrical Engineering & Computer Science'), ('deans-office', "Dean's Office")], help_text='Primary department affiliation', max_length=20, null=True, verbose_name='Department')),
                ('granting_agency', models.CharField(max_length=300)),
                ('program', models.CharField(blank=True, help_text='Funding program within the agency', max_length=300)),
                ('dollar_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('principal_investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_grants', to='core.person', verbose_name='Principal Investigator')),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'Grants',
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_conferred', models.CharField(choices=[('BS', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('MS', 'Master of Science'), ('MA', 'Master of Arts'), ('PhD', 'Doctor of Philosophy'), ('Other', 'Other')], max_length=10)),
                ('focus', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor')], default='major', max_length=10)),
                ('name', models.CharField(max_length=300)),
                ('department', models.CharField(blank=True, choices=[('biology', 'Biology'), ('chemistry', 'Chemistry'), ('mathematics', 'Mathematical Sciences'), ('physics', 'Physics'), ('asme', 'Aerospace & Mechanical Engineering'), ('ceet', 'Chemical Engineering & Environmental Toxicology'), ('cets', 'Civil Engineering & Transportation Studies'), ('eecs', 'Electrical Engineering & Computer Science'), ('deans-office', "Dean's Office")], help_text='Primary department affiliation', max_length=20, null=True, verbose_name='Department')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('certificate', 'Certficate')], db_index=True, default='undergraduate', max_length=15, verbose_name='Graduate / Undergraduate')),
                ('description', models.TextField(blank=True)),
                ('admission_requirements', models.TextField(blank=True)),
                ('credit_hours', models.PositiveSmallIntegerField(default=120)),
                ('major_requirements', models.TextField(blank=True, help_text='Narrative or course list for required courses')),
                ('other_requirements', models.TextField(blank=True)),
                ('electives', models.TextField(blank=True)),
                ('degree_plan', models.TextField(blank=True, help_text='Semester-by-semester degree plan narrative or link')),
                ('elective_courses', models.ManyToManyField(blank=True, related_name='elective_in_programs', to='core.course', verbose_name='Elective Courses')),
                ('required_courses', models.ManyToManyField(blank=True, related_name='required_by_programs', to='core.course', verbose_name='Required Courses')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('publications', models.TextField(blank=True, help_text='List or description of publications; structured DOIs, or link to external source')),
                ('capabilities', models.TextField(blank=True, help_text='Research capabilities and expertise')),
                ('equipment', models.TextField(blank=True, verbose_name='Equipment & Instrumentation')),
                ('personnel', models.TextField(blank=True, help_text='Additional personnel not captured as Persons')),
                ('safety_requirements', models.TextField(blank=True)),
                ('co_investigators', models.ManyToManyField(blank=True, related_name='co_i_research', to='core.person', verbose_name='Co-Investigators')),
                ('grants', models.ManyToManyField(blank=True, related_name='research_projects', to='core.grant')),
                ('principal_investigator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pi_research', to='core.person', verbose_name='Principal Investigator')),
                ('student_researchers', models.ManyToManyField(blank=True, related_name='student_research', to='core.person', verbose_name='Student Researchers')),
            ],
            options={
                'verbose_name': 'Research Group',
                'verbose_name_plural': 'Research Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, verbose_name='Website URL')),
                ('unit_type', models.CharField(choices=[('administrative', 'Administrative'), ('academic', 'Academic'), ('research', 'Research')], db_index=True, default='academic', max_length=20, verbose_name='Type')),
                ('room', models.CharField(blank=True, help_text='e.g. TECH 201', max_length=50, null=True, verbose_name='Room')),
                ('interim', models.BooleanField(default=False, verbose_name='Principal is Interim')),
                ('principal_email', models.EmailField(blank=True, max_length=254)),
                ('principal_phone', models.CharField(blank=True, max_length=30)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('admin_phone', models.CharField(blank=True, max_length=30)),
                ('admin_fax', models.CharField(blank=True, max_length=30)),
                ('logo', models.URLField(blank=True, verbose_name='Logo URL')),
                ('photo', models.URLField(blank=True, verbose_name='Photo URL')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_units', to='core.person', verbose_name='Administrative Contact')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_units', to='core.person', verbose_name='Principal / Head')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('office', 'Office'), ('classroom', 'Classroom'), ('lab', 'Laboratory'), ('conference', 'Conference Room'), ('storage', 'Storage'), ('server', 'Server Room'), ('other', 'Other')], default='office', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('occupant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_rooms', to='core.person', verbose_name='Primary Occupant')),
                ('point_of_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms_as_contact', to='core.person', verbose_name='Point of Contact')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='core.unit', verbose_name='Unit Affiliation')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['room_number'],
            },
        ),
    ]
