# Generated by Django 6.0.3 on 2026-03-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='biography',
            field=models.TextField(blank=True, verbose_name='Biography (plain text or markdown)'),
        ),
    ]
