# Generated by Django 6.0.3 on 2026-04-26 19:41

from django.db import migrations

SLUG_TO_ABBREV = {
    'biology':     'BIOL',
    'chemistry':   'CHEM',
    'mathematics': 'MATH',
    'physics':     'PHYS',
    'asme':        'ASME',
    'ceet':        'CEET',
    'cets':        'CETS',
    'eecs':        'EECS',
    'deans-office':'ADMIN',
}


def convert_slugs_to_abbrevs(apps, schema_editor):
    Course = apps.get_model('core', 'Course')
    Program = apps.get_model('core', 'Program')
    for slug, abbrev in SLUG_TO_ABBREV.items():
        Course.objects.filter(department=slug).update(department=abbrev)
        Program.objects.filter(department=slug).update(department=abbrev)


def convert_abbrevs_to_slugs(apps, schema_editor):
    ABBREV_TO_SLUG = {v: k for k, v in SLUG_TO_ABBREV.items()}
    Course = apps.get_model('core', 'Course')
    Program = apps.get_model('core', 'Program')
    for abbrev, slug in ABBREV_TO_SLUG.items():
        Course.objects.filter(department=abbrev).update(department=slug)
        Program.objects.filter(department=abbrev).update(department=slug)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_program_department_abbrev'),
    ]

    operations = [
        migrations.RunPython(convert_slugs_to_abbrevs, reverse_code=convert_abbrevs_to_slugs),
    ]
