# Generated by Django 6.0.3 on 2026-04-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_convert_dept_slug_to_abbrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='unit_photos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='unit_photos/', verbose_name='Photo'),
        ),
    ]
