# Generated by Django 6.0.3 on 2026-04-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_unit_logo_alter_unit_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='source_url',
            field=models.URLField(blank=True, help_text='orgin url in University website'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='unitexport DJANGO_SETTINGS_MODULE=coset.settings.dev _photos/', verbose_name='Photo'),
        ),
    ]
