# Generated by Django 6.0.3 on 2026-04-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_program_source_url_alter_unit_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='elective_courses',
        ),
        migrations.RemoveField(
            model_name='program',
            name='focus',
        ),
        migrations.RemoveField(
            model_name='program',
            name='level',
        ),
        migrations.RemoveField(
            model_name='program',
            name='required_courses',
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, choices=[('BIOL', 'Biology'), ('CHEM', 'Chemistry'), ('MATH', 'Mathematical Sciences'), ('PHYS', 'Physics'), ('AMEN', 'Aerospace & Mechanical Engineering'), ('CEET', 'Chemical Engineering & Environmental Toxicology'), ('CETS', 'Civil Engineering & Transportation Studies'), ('EECS', 'Electrical Engineering & Computer Science'), ('ADMIN', "Dean's Office")], help_text='Primary department affiliation', max_length=20, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.CharField(blank=True, choices=[('BIOL', 'Biology'), ('CHEM', 'Chemistry'), ('MATH', 'Mathematical Sciences'), ('PHYS', 'Physics'), ('AMEN', 'Aerospace & Mechanical Engineering'), ('CEET', 'Chemical Engineering & Environmental Toxicology'), ('CETS', 'Civil Engineering & Transportation Studies'), ('EECS', 'Electrical Engineering & Computer Science'), ('ADMIN', "Dean's Office")], help_text='Primary department affiliation', max_length=20, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='program',
            name='degree_conferred',
            field=models.CharField(choices=[('BS', 'Bachelor of Science'), ('MS', 'Master of Science'), ('PHD', 'Doctor of Philosophy'), ('MINOR', 'Minor'), ('CERT', 'Certificate'), ('4+1', 'Accelerated 4+1 BS/MS'), ('OTHER', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.CharField(blank=True, choices=[('BIOL', 'Biology'), ('CHEM', 'Chemistry'), ('MATH', 'Mathematical Sciences'), ('PHYS', 'Physics'), ('AMEN', 'Aerospace & Mechanical Engineering'), ('CEET', 'Chemical Engineering & Environmental Toxicology'), ('CETS', 'Civil Engineering & Transportation Studies'), ('EECS', 'Electrical Engineering & Computer Science'), ('ADMIN', "Dean's Office")], help_text='Primary department affiliation', max_length=20, null=True, verbose_name='Department'),
        ),
    ]
