# Generated by Django 6.0.3 on 2026-05-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_course_department_alter_person_department_and_more'),
        ('core', '0006_remove_program_elective_courses_remove_program_focus_and_more'),
    ]

    operations = [
    ]
