# Generated by Django 6.0.3 on 2026-04-24 02:15

import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HeroPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='InterestFormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsEventIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_intro', models.CharField(blank=True, default='The latest news, announcements, and events from COSET', max_length=300)),
            ],
            options={
                'verbose_name': 'News & Events Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PersonIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='PostSectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('floating_image', 5), ('table', 6)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'default': 'Some', 'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol', 'hr', 'document-link', 'image', 'blockquote', 'subscript', 'superscript']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional image caption', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Float Left'), ('right', 'Float Right')]}), 4: ('wagtail.blocks.IntegerBlock', (), {'default': 50, 'help_text': 'Width of the image as a percentage of the container', 'max_value': 100, 'min_value': 10}), 5: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alignment', 3), ('width_percent', 4)]], {}), 6: ('wagtail.contrib.table_block.blocks.TableBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, default='Welcome to the COSET website!', max_length=255)),
                ('hero_cta_text', models.CharField(blank=True, default='Explore our courses and people', max_length=255)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(choices=[('event', 'Event'), ('announcement', 'Announcement'), ('research', 'Research'), ('award', 'Award & Recognition'), ('partnership', 'Partnership'), ('student', 'Student Achievement'), ('faculty', 'Faculty Spotlight'), ('general', 'General Post'), ('testimonial', 'Testimonial'), ('scholarship', 'Scholarship'), ('seminar', 'Seminar'), ('internship', 'Internship')], default='general', max_length=50)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date & Time')),
                ('author', models.CharField(blank=True, help_text='For News: the person(s) involved in the news item. For Events: the organizer or featured speaker.', max_length=200)),
                ('location', models.CharField(blank=True, help_text='For Events: the event location. For News: optional location associated with the news item.', max_length=300)),
                ('url', models.URLField(blank=True, help_text='Link to RSVP / registration form/ Optional Google Maps or venue URL.')),
                ('unit', models.CharField(blank=True, help_text='Optional unit/department associated with this news item.', max_length=100)),
                ('summary', models.TextField(help_text='Short summary shown on the index card (max 400 chars).', max_length=400)),
                ('body', wagtail.fields.RichTextField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog Post',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePageTestimonialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_posts', to='base.homepage')),
                ('testimonial_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.postpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePageFeaturedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_posts', to='base.homepage')),
                ('featured_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.postpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
