# Generated by Django 6.0.3 on 2026-03-23 07:41

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('floating_image', 5)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional image caption', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Float Left'), ('right', 'Float Right')]}), 4: ('wagtail.blocks.IntegerBlock', (), {'default': 50, 'help_text': 'Width of the image as a percentage of the container', 'max_value': 100, 'min_value': 10}), 5: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alignment', 3), ('width_percent', 4)]], {})}),
        ),
    ]
