# Generated by Django 6.0.3 on 2026-04-27 21:01

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_departmentfacultypage_departmentindexpage_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('paragraph', 0), ('floating_image', 5), ('table', 6), ('markdown', 7)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol', 'hr', 'document-link', 'image', 'blockquote', 'subscript', 'superscript']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional image caption', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Float Left'), ('right', 'Float Right')]}), 4: ('wagtail.blocks.IntegerBlock', (), {'default': 50, 'help_text': 'Width of the image as a percentage of the container', 'max_value': 100, 'min_value': 10}), 5: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alignment', 3), ('width_percent', 4)]], {}), 6: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 7: ('wagtailmarkdown.blocks.MarkdownBlock', (), {'icon': 'code'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
