# Generated by Django 6.0.3 on 2026-04-17 04:44

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_interestformpage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEventIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_intro', models.CharField(blank=True, default='The latest news, announcements, and events from COSET', max_length=300)),
            ],
            options={
                'verbose_name': 'News & Events Index Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('floating_image', 5), ('table', 6)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'default': 'Some', 'features': ['h2', 'h3', 'h4', 'bold', 'italic', 'link', 'ul', 'ol', 'hr', 'document-link', 'image', 'blockquote', 'subscript', 'superscript']}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional image caption', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Float Left'), ('right', 'Float Right')]}), 4: ('wagtail.blocks.IntegerBlock', (), {'default': 50, 'help_text': 'Width of the image as a percentage of the container', 'max_value': 100, 'min_value': 10}), 5: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2), ('alignment', 3), ('width_percent', 4)]], {}), 6: ('wagtail.contrib.table_block.blocks.TableBlock', (), {})}),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('start_datetime', models.DateTimeField(verbose_name='Start Date & Time')),
                ('location', models.CharField(blank=True, max_length=300)),
                ('location_url', models.URLField(blank=True, help_text='Optional Google Maps or venue URL.')),
                ('summary', models.TextField(help_text='Short summary shown on the index card.', max_length=400)),
                ('body', wagtail.fields.RichTextField()),
                ('registration_url', models.URLField(blank=True, help_text='Link to RSVP / registration form.')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Event',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(choices=[('announcement', 'Announcement'), ('research', 'Research'), ('award', 'Award & Recognition'), ('partnership', 'Partnership'), ('student', 'Student Achievement'), ('faculty', 'Faculty Spotlight'), ('general', 'General News')], default='general', max_length=50)),
                ('publish_date', models.DateField(default=django.utils.timezone.now, verbose_name='Publish Date')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(help_text='Short summary shown on the index card (max 400 chars).', max_length=400)),
                ('body', wagtail.fields.RichTextField()),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'News Article',
            },
            bases=('wagtailcore.page',),
        ),
    ]
