# Generated by Django 6.0.3 on 2026-04-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_newseventindexpage_alter_standardpage_body_eventpage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpage',
            old_name='start_datetime',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='eventpage',
            old_name='hero_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='newspage',
            old_name='publish_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='newspage',
            old_name='hero_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='registration_url',
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='location_url',
            field=models.URLField(blank=True, help_text='Link to RSVP / registration form/ Optional Google Maps or venue URL.'),
        ),
    ]
