# Generated by Django 6.0.3 on 2026-04-19 18:44

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_start_datetime_eventpage_datetime_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='newspage',
            name='page_ptr',
        ),
        migrations.CreateModel(
            name='PostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(choices=[('event', 'Event'), ('announcement', 'Announcement'), ('research', 'Research'), ('award', 'Award & Recognition'), ('partnership', 'Partnership'), ('student', 'Student Achievement'), ('faculty', 'Faculty Spotlight'), ('general', 'General Post'), ('testimonial', 'Testimonial'), ('scholarship', 'Scholarship'), ('seminar', 'Seminar'), ('internship', 'Internship')], default='general', max_length=50)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date & Time')),
                ('author', models.CharField(blank=True, help_text='For News: the person(s) involved in the news item. For Events: the organizer or featured speaker.', max_length=200)),
                ('location', models.CharField(blank=True, help_text='For Events: the event location. For News: optional location associated with the news item.', max_length=300)),
                ('url', models.URLField(blank=True, help_text='Link to RSVP / registration form/ Optional Google Maps or venue URL.')),
                ('unit', models.CharField(blank=True, help_text='Optional unit/department associated with this news item.', max_length=100)),
                ('summary', models.TextField(help_text='Short summary shown on the index card (max 400 chars).', max_length=400)),
                ('body', wagtail.fields.RichTextField()),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog Post',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='EventPage',
        ),
        migrations.DeleteModel(
            name='NewsPage',
        ),
    ]
