# Generated by Django 6.0.3 on 2026-04-20 04:35

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_postsectionpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_posts',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='featured_on_homepage', to='base.postpage'),
        ),
    ]
