# Generated by Django 6.0.3 on 2026-04-20 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_homepage_featured_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_posts',
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_post_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.postpage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_post_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.postpage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_post_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.postpage'),
        ),
    ]
