# Generated by Django 6.0.3 on 2026-04-20 05:55

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_homepage_featured_posts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_post_1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_post_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='featured_post_3',
        ),
        migrations.CreateModel(
            name='HomePageFeaturedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('featured_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.postpage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_posts', to='base.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
