# Generated by Django 6.0.3 on 2026-04-20 06:58

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_homepage_featured_post_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageTestimonialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_posts', to='base.homepage')),
                ('testimonial_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.postpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
